title: Myounghoon Jang
author: Myounghoon Jang
# email: jangjang4080@gmail.com
description: > # this means to ignore newlines until "twitter_username:"
  About Me, Projects

port:             50210
host:             0.0.0.0

# social links
# twitter_username: jekyllrb
# github_username:  jangjang4080
google_analytics: UA-126911269-4
# rss: rss
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
# linkedin_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
# youtube_channel_name: CloudCannon
# telegram_username: jekyll
# googleplus_username: +jekyll
# microdotblog_username: jekyll

# Mastodon instances
# mastodon:
# - username: jekyll
#   instance: example.com
# - username: jekyll2
#   instance: example.com


show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
# minima:
#   date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
- projects.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
